services:
  holiday-cn:
    build: .
    container_name: holiday-cn
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - CRON_SCHEDULE=0 12 * * *  # 定时更新时间，默认每天中午 12 点
    restart: unless-stopped
