name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Setup git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
      - name: Test
        run: poetry run coverage run -m pytest
      - name: Lint
        run: poetry run flake8 holiday_cn tests
      - name: Update (main)
        if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: poetry run coverage run -a -m holiday_cn.entry --release
      - name: Update
        if: ${{ !(github.ref == 'refs/heads/main' && github.event_name != 'pull_request') }}
        run: poetry run coverage run -a -m holiday_cn.entry
